[BIA-1101] Code and Dependency Review Workflows (Engage Online Learners)
Ed-Fi-Alliance-OSS/Engage-Online-Learners-Starter-Kit pull request #46
Opened 2022-12-23 14:29 UTC by jegasape

- Code and Dependency Review Workflows (Engage Online Learners)

2023-01-09 14:44 UTC, DavidJGapCR commented
Based on the description on the ticket we need 2 things:
1. Dependency Scan
2. A linter to run PSScriptAnalyzer.

I see you included the first one, but what about the second one?

2023-01-09 14:45 UTC, DavidJGapCR requested changes
One action is failing.

2023-01-24 18:31 UTC, stephenfuqua commented on .github/workflows/codeql.yml
> +          echo '::notice:: No files found'
```suggestion
          echo '::notice:: No files were found for CodeQL analysis'
```

2023-01-24 18:32 UTC, stephenfuqua approved these changes

2023-01-24 18:56 UTC, DavidJGapCR approved these changes

2023-01-24 18:59 UTC, merged